server:
  port: 1111
spring:
  datasource:
    url: jdbc:mysql://localhost:5467/DBase?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: false

